version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
