version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    cooldown:
      default-days: 14
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
