name: Release notes comments

on:
  workflow_run:
    workflows: [Release notes, Release notes changelog file]
    types: [completed]

permissions: {}

concurrency:
  group: release-notes-comments-${{ github.event.workflow_run.head_repository.full_name }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  comment:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion != 'cancelled'
    permissions:
      actions: read
      pull-requests: write
    uses: elastic/docs-actions/.github/workflows/release-notes-comments.yml@v1
