name: Release notes changelog file

on:
  workflow_run:
    workflows: [Release notes]
    types: [completed]

permissions: {}

jobs:
  changelog-file:
    permissions:
      actions: write
      contents: write
      id-token: write
      packages: read
      pull-requests: write
    uses: elastic/docs-actions/.github/workflows/release-notes-changelog-file.yml@v1
