name: Changelog generate

on:
  workflow_call:
    inputs:
      config:
        description: 'Path to changelog.yml configuration file'
        type: string
        default: 'docs/changelog.yml'

concurrency:
  group: changelog-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  generate:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        uses: elastic/docs-actions/changelog/generate@v1
        with:
          config: ${{ inputs.config }}
