name: Changelog upload

on:
  workflow_call:

permissions: {}

concurrency:
  group: changelog-upload-${{ inputs.pr-number }}
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Upload changelog
        uses: elastic/docs-actions/changelog/upload@v1
