name: Docs Preview Cleanup

on:
  workflow_call: ~

permissions:
  contents: none
  deployments: write
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-slim
    steps:
      - uses: elastic/docs-actions/docs-builder/preview/cleanup@v1
        with:
          pr-number: ${{ github.event.pull_request.number }}
