name: test-docs-builder-setup

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs-builder/setup/**'
      - '.github/workflows/test-docs-builder-setup.yml'
  push:
    branches:
      - main
    paths:
      - 'docs-builder/setup/**'
      - '.github/workflows/test-docs-builder-setup.yml'

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: ${{ matrix.runner }} / version=${{ matrix.version || 'default' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        version: [edge, latest, '0.100.0', null]
        runner: [ubuntu-24.04, ubuntu-26.04]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./docs-builder/setup
        with:
          version: ${{ matrix.version }}
      - run: docs-builder --version
